{"uuid":"1523e9cf-4e2d-4222-ab81-8ec5a2f0e03f","historyId":"76c347ddf5f27c890d23b9369ca4fd40","testCaseId":"[engine:junit-jupiter]/[class:org.academo.academo.London.service.SubmissionServiceTest]/[method:getByTaskId_DataAccessException()]","testCaseName":"Get By Task ID - Throws DatabaseServiceException on database error","fullName":"org.academo.academo.London.service.SubmissionServiceTest.getByTaskId_DataAccessException","labels":[{"name":"tag","value":"unit"},{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:org.academo.academo.London.service.SubmissionServiceTest]/[method:getByTaskId_DataAccessException()]"},{"name":"host","value":"Rockio"},{"name":"thread","value":"68025@Rockio.main(3)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"org.academo.academo.London.service.SubmissionServiceTest"},{"name":"testClass","value":"org.academo.academo.London.service.SubmissionServiceTest"},{"name":"testMethod","value":"getByTaskId_DataAccessException"},{"name":"suite","value":"Submission Service Tests"}],"links":[],"name":"Get By Task ID - Throws DatabaseServiceException on database error","status":"passed","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1757418977028,"stop":1757418977029}