{"uuid":"f432e25c-3333-4215-937b-b6d20c7c5b77","historyId":"76c347ddf5f27c890d23b9369ca4fd40","testCaseId":"[engine:junit-jupiter]/[class:org.academo.academo.London.service.SubmissionServiceTest]/[method:getByTaskId_DataAccessException()]","testCaseName":"Get By Task ID - Throws DatabaseServiceException on database error","fullName":"org.academo.academo.London.service.SubmissionServiceTest.getByTaskId_DataAccessException","labels":[{"name":"tag","value":"unit"},{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:org.academo.academo.London.service.SubmissionServiceTest]/[method:getByTaskId_DataAccessException()]"},{"name":"host","value":"Rockio"},{"name":"thread","value":"5035@Rockio.main(3)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"org.academo.academo.London.service.SubmissionServiceTest"},{"name":"testClass","value":"org.academo.academo.London.service.SubmissionServiceTest"},{"name":"testMethod","value":"getByTaskId_DataAccessException"},{"name":"suite","value":"Submission Service Tests"}],"links":[],"name":"Get By Task ID - Throws DatabaseServiceException on database error","status":"passed","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1757150045568,"stop":1757150045570}